[package]
name = "pq_cairo_merkle_poseidon"
version = "0.1.0"
edition = "2024_07"

[lib]
sierra = true
casm = false

[[target.executable]]
name = "pq_cairo_merkle_poseidon"
function = "pq_cairo_merkle_poseidon::main"

[[target.executable]]
name = "pq_cairo_merkle_poseidon_l1_fact"
function = "pq_cairo_merkle_poseidon::main_l1_fact"

[cairo]
enable-gas = false

[dependencies]
cairo_execute = ">=2.18.0"

[dev-dependencies]
cairo_test = "2.18.0"
