published_root = "0x01fc64bed90c55b193ec54e851cd13888d45293f2a2e4efdf83581f39df9c615"

[merkle_proof]
indices = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
length = 0
siblings = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[[new_notes]]
nonce = 0
owner = 0
value = 1

[[new_notes]]
nonce = 0
owner = 0
value = 3

[old_note]
nonce = 0
owner = 0
value = 5

[return]
new_commitments = [0, 0]
