[package]
name = "atlantic_stwo_blake_finalize64_smoke"
version = "0.1.0"
edition = "2024_07"

[lib]
sierra = true
casm = false

[[target.executable]]
name = "atlantic_stwo_blake_finalize64_smoke"
function = "atlantic_stwo_blake_finalize64_smoke::main"
sierra = true

[dependencies]
stwo_verifier_utils = { path = "../verifier_utils" }
cairo_execute = ">=2.18.0"
