[package]
name = "atlantic_stwo_claim_builtins"
version = "0.1.0"
edition = "2024_07"

[lib]
sierra = true
casm = false

[[target.executable]]
name = "atlantic_stwo_claim_builtins"
function = "atlantic_stwo_claim_builtins::main"
sierra = true

[features]
poseidon252_verifier = ["stwo_cairo_air/poseidon252_verifier"]
qm31_opcode = ["stwo_cairo_air/qm31_opcode"]

[dependencies]
stwo_cairo_air = { path = "../cairo_air" }
cairo_execute = ">=2.18.0"
