published_root = "0x2a7cec1480256063ea182a8bf73400768305bf001a0dd0d5fa6762554b846321"
value = 5

[merkle_proof]
indices = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
length = 0
siblings = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[note]
asset = 1
nonce = 0
owner = "419779223150668528406796704116317490430959102897"
value = 5
